# Generated by Django 4.1.5 on 2023-01-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourAI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youraiuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
