# Generated by Django 4.1.5 on 2023-01-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourAI', '0002_youraiuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='youraiuser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
