# Generated by Django 4.1.5 on 2023-01-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourAI', '0003_youraiuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='youraiuser',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
