# Generated by Django 4.1.5 on 2023-01-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourAI', '0004_youraiuser_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='youraiuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
