# Generated by Django 4.1.5 on 2023-01-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YourAI', '0005_youraiuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youraiuser',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='youraiuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='youraiuser',
            name='last_login',
        ),
    ]
