# Generated by Django 4.1.5 on 2023-01-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourAI', '0006_remove_youraiuser_is_authenticated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youraiuser',
            name='expiry_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='youraiuser',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
