# Generated by Django 4.1.5 on 2023-02-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourAI', '0007_alter_youraiuser_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youraiuser',
            name='api_count',
            field=models.IntegerField(default=20),
        ),
    ]
