# Generated by Django 4.1.5 on 2023-02-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourAI', '0008_youraiuser_api_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youraiuser',
            name='api_count',
        ),
        migrations.RemoveField(
            model_name='youraiuser',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='youraiuser',
            name='pack',
        ),
        migrations.AddField(
            model_name='youraiuser',
            name='coins',
            field=models.IntegerField(default=20),
        ),
    ]
