# Generated by Django 4.1.5 on 2023-02-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourAI', '0009_remove_youraiuser_api_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youraiuser',
            name='coins',
            field=models.FloatField(default=20),
        ),
    ]
